# Generated by Django 3.1.1 on 2020-12-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_auto_20201010_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccion',
            name='time',
            field=models.TimeField(),
        ),
    ]
