# Generated by Django 3.1.1 on 2020-12-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_auto_20201207_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='butacas',
            old_name='proyección',
            new_name='proyeccion',
        ),
    ]
